dataset:
  dataset_name: kazushiadachi/human-portrait-or-not-128128-binary-and-rgb
  download: False
  split_data: False

tf_cnn_classic:
  train: False
  test: True

torch_cnn_classic:
  train: False
  test: True